name: e-commerce-bluefoot
services:
  postgres:
    image: postgres:16-alpine
    container_name: e-commerce-bluefoot-DB
    restart: always

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: api_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
